{"name": "Получение ошибки при авторизации несуществующим курьером.", "status": "passed", "description": "Тест для проверки получения ошибки при попытке авторизоваться несуществующим курьером.", "steps": [{"name": "Получить пароль созданного курьера.", "status": "passed", "start": 1748126770770, "stop": 1748126770770}, {"name": "Создать рандомный логин.", "status": "passed", "start": 1748126770770, "stop": 1748126770770}, {"name": "Отправить запрос на авторизацию с несуществующим логином.", "status": "passed", "start": 1748126770770, "stop": 1748126770883}, {"name": "Проверить код и сообщение об ошибке ответа.", "status": "passed", "start": 1748126770883, "stop": 1748126770883}], "start": 1748126770770, "stop": 1748126770883, "uuid": "a4b836f7-9804-4602-a280-a0b28e844c2c", "historyId": "4922019048d6b6b2535811b66859ad46", "testCaseId": "4922019048d6b6b2535811b66859ad46", "fullName": "tests.courier_login_test.TestCourierLogin#test_login_with_nonexistent_user_returns_error_received_an_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "courier_login_test"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-G7OKOON"}, {"name": "thread", "value": "15400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier_login_test"}], "links": [{"type": "link", "url": "https://qa-scooter.praktikum-services.ru/docs/", "name": "API документация"}]}