{"name": "Получение ошибки при авторизации несуществующим курьером.", "status": "passed", "description": "Тест для проверки получения ошибки при попытке авторизоваться несуществующим курьером.", "steps": [{"name": "Получить пароль созданного курьера.", "status": "passed", "start": 1748125885633, "stop": 1748125885634}, {"name": "Создать рандомный логин.", "status": "passed", "start": 1748125885634, "stop": 1748125885634}, {"name": "Отправить запрос на авторизацию с несуществующим логином.", "status": "passed", "start": 1748125885634, "stop": 1748125885775}, {"name": "Проверить код и сообщение об ошибке ответа.", "status": "passed", "start": 1748125885775, "stop": 1748125885775}], "start": 1748125885633, "stop": 1748125885776, "uuid": "db7271a1-cb4e-4053-be5b-49eac16a0187", "historyId": "4922019048d6b6b2535811b66859ad46", "testCaseId": "4922019048d6b6b2535811b66859ad46", "fullName": "tests.courier_login_test.TestCourierLogin#test_login_with_nonexistent_user_returns_error_received_an_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "courier_login_test"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-G7OKOON"}, {"name": "thread", "value": "10316-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier_login_test"}], "links": [{"type": "link", "url": "https://qa-scooter.praktikum-services.ru/docs/", "name": "API документация"}]}